"""
ثابت‌های غیررفتاری NDS برای طلا
فقط شامل نگاشت‌ها/کلیدهای بدون اعداد قابل تنظیم
"""

# ==================== تبدیل نام سشن‌ها ====================

SESSION_MAPPING = {
    'LONDON_OPEN': 'LONDON',
    'LONDON_CORE': 'LONDON',
    'NY_OPEN': 'NEW_YORK',
    'NY_CORE': 'NEW_YORK',
    'OVERLAP_PEAK': 'OVERLAP',
    'ASIA': 'ASIA',
    'DEAD_ZONE': 'OTHER'
}

# ==================== کلیدهای مجاز برای تنظیمات تحلیل ====================

ANALYSIS_CONFIG_KEYS = frozenset({
    'ATR_WINDOW',
    'ADX_WINDOW',
    'ADX_THRESHOLD_WEAK',
    'ADX_THRESHOLD_STRONG',
    'SWING_PERIOD',
    'ATR_SL_MULTIPLIER',
    'MIN_RVOL_SCALPING',
    'SWING_MIN_CONFIDENCE',
    'MIN_STRUCTURE_SCORE',
    'SCALPING_MAX_BARS_BACK',
    'SCALPING_MAX_DISTANCE_ATR',
    'SCALPING_MIN_FVG_SIZE_ATR',
    'DAILY_ATR_FACTOR',
    'ATR_MULTIPLIER',
    'RVOL_THRESHOLD',
    'FVG_VOLUME_CONFIRMATION',
    'MIN_ATR_DISTANCE_MULTIPLIER',
    'FVG_MIN_SIZE_MULTIPLIER',
    'OB_MIN_SIZE_MULTIPLIER',
    'MIN_SWEEP_PENETRATION_MULTIPLIER',
    'MIN_CANDLE_RANGE_MULTIPLIER',
    'SCALPING_MIN_CONFIDENCE',
    'MIN_CONFIDENCE',
    'FIXED_BUFFER',
    'RANGE_TOLERANCE',
    'ENTRY_FACTOR',
    'MIN_SESSION_WEIGHT',
    'DEBUG_ANALYZER',
    'ENABLE_LEGACY_SWING_ENTRY',
    'FLOW_STOP_BUFFER_ATR',
    'FLOW_RETEST_POLICY',
    'FLOW_TOUCH_PENETRATION_ATR',
    'FLOW_MAX_TOUCHES',
    'FLOW_TOUCH_PENALTY',
    'FLOW_TOUCH_EXIT_ATR',
    'FLOW_TOUCH_EXIT_PIPS',
    'FLOW_ZONE_KEY_PRECISION',
    'FLOW_NEAREST_ZONES',
    'BRK_MAX_DIST_ATR',
    'BRK_MAX_AGE_BARS',
    'IFVG_MAX_DIST_ATR',
    'IFVG_MAX_AGE_BARS',
    'MOMO_ADX_MIN',
    'MOMO_TIME_START',
    'MOMO_TIME_END',
    'MOMO_SESSION_ONLY',
    'MOMO_SESSION_ALLOWLIST',
    'MOMO_BUFFER_ATR_MULT',
    'MOMO_BUFFER_MIN_PIPS',
    'SCALP_ATR_SL_MULT',
    'SL_MIN_PIPS',
    'MIN_SL_PIPS',
    'SL_MAX_PIPS',
    'TP1_PIPS',
    'TP2_PIPS',
    'TP2_ENABLED',
    'SPREAD_MAX_PIPS',
})
